### ISSUE TITLE
Package shouldn't depend on plone.app.z3cform

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.schema#12]
Which in turn, pulls Zope, as stated in https://github.com/plone/plone.registry/pull/22#issuecomment-819664179

A possible solution, hinted in https://github.com/plone/plone.registry/pull/22#issuecomment-819528414

Needed for https://github.com/plone/plone.registry/pull/22

**Comment by mauritsvanrees** [comment]
See also https://github.com/plone/plone.base/issues/9, especially [this comment](https://github.com/plone/plone.base/issues/9#issuecomment-1119593474) by @davisagli. If I understand that correctly, it should be okay to replace `IPloneFormLayer` with something else, I guess simply `Interface`. Is that correct David?
cc @jensens 

Sounds slightly risky for a beta stage, but I think I would accept it, as it helps reduce dependencies.

**Comment by davisagli** [comment]
@mauritsvanrees I would try `z3c.form.interfaces.IFormLayer`, which is what the built-in widgets in z3c.form use.

**Comment by jensens** [comment]
Or move IPloneFormLayer to plone.z3c.form?

**Comment by davisagli** [comment]
@jensens That could also work, but note that IPloneFormLayer is currently applied as a browser layer in plone.app.z3cform's GS profile, and plone.z3cform does not have a GS profile or assume the use of CMF and GenericSetup.

I guess it would be okay to move the definition of the interface to plone.z3cform and still apply the browser layer in plone.app.z3cform. That would make it harder to write a test for the widgets in plone.schema though.

**Comment by jensens** [comment]
yeah. *sigh* The whole construct with plone[.app].z3cform and related packages would need a cleanup dependency wise (or a merger). touching it is always a PITA.
